/**
 * ISO 4217 currency catalog — code → { name, symbol }.
 *
 * Used to render any currency a configured fiat-rate endpoint returns (so search
 * works for every queryable currency, not a hand-picked subset). Codes missing
 * here still display, falling back to the bare code as both name and symbol.
 *
 * Symbols are the commonly-used display glyph; where a currency has no distinct
 * glyph we use the ISO code (e.g. "CHF", "PLN") which is the conventional display.
 */
export interface CurrencyMeta { name: string; symbol: string }

export const CURRENCY_CATALOG: Record<string, CurrencyMeta> = {
  USD: { name: 'US Dollar', symbol: '$' },
  EUR: { name: 'Euro', symbol: '€' },
  JPY: { name: 'Japanese Yen', symbol: '¥' },
  GBP: { name: 'British Pound', symbol: '£' },
  CNY: { name: 'Chinese Yuan', symbol: '¥' },
  AUD: { name: 'Australian Dollar', symbol: 'A$' },
  CAD: { name: 'Canadian Dollar', symbol: 'C$' },
  CHF: { name: 'Swiss Franc', symbol: 'CHF' },
  HKD: { name: 'Hong Kong Dollar', symbol: 'HK$' },
  SGD: { name: 'Singapore Dollar', symbol: 'S$' },
  KRW: { name: 'South Korean Won', symbol: '₩' },
  INR: { name: 'Indian Rupee', symbol: '₹' },
  BRL: { name: 'Brazilian Real', symbol: 'R$' },
  MXN: { name: 'Mexican Peso', symbol: 'MX$' },
  ARS: { name: 'Argentine Peso', symbol: 'AR$' },
  IDR: { name: 'Indonesian Rupiah', symbol: 'Rp' },
  TRY: { name: 'Turkish Lira', symbol: '₺' },
  PHP: { name: 'Philippine Peso', symbol: '₱' },
  ZAR: { name: 'South African Rand', symbol: 'R' },
  THB: { name: 'Thai Baht', symbol: '฿' },
  MYR: { name: 'Malaysian Ringgit', symbol: 'RM' },
  NZD: { name: 'New Zealand Dollar', symbol: 'NZ$' },
  PLN: { name: 'Polish Złoty', symbol: 'zł' },
  SEK: { name: 'Swedish Krona', symbol: 'kr' },
  NOK: { name: 'Norwegian Krone', symbol: 'kr' },
  DKK: { name: 'Danish Krone', symbol: 'kr' },
  CZK: { name: 'Czech Koruna', symbol: 'Kč' },
  HUF: { name: 'Hungarian Forint', symbol: 'Ft' },
  RON: { name: 'Romanian Leu', symbol: 'lei' },
  BGN: { name: 'Bulgarian Lev', symbol: 'лв' },
  ILS: { name: 'Israeli New Shekel', symbol: '₪' },
  ISK: { name: 'Icelandic Króna', symbol: 'kr' },
  AED: { name: 'UAE Dirham', symbol: 'د.إ' },
  SAR: { name: 'Saudi Riyal', symbol: '﷼' },
  QAR: { name: 'Qatari Riyal', symbol: '﷼' },
  KWD: { name: 'Kuwaiti Dinar', symbol: 'د.ك' },
  BHD: { name: 'Bahraini Dinar', symbol: '.د.ب' },
  OMR: { name: 'Omani Rial', symbol: '﷼' },
  JOD: { name: 'Jordanian Dinar', symbol: 'د.ا' },
  LBP: { name: 'Lebanese Pound', symbol: 'ل.ل' },
  EGP: { name: 'Egyptian Pound', symbol: 'E£' },
  MAD: { name: 'Moroccan Dirham', symbol: 'د.م.' },
  DZD: { name: 'Algerian Dinar', symbol: 'دج' },
  TND: { name: 'Tunisian Dinar', symbol: 'د.ت' },
  NGN: { name: 'Nigerian Naira', symbol: '₦' },
  GHS: { name: 'Ghanaian Cedi', symbol: '₵' },
  KES: { name: 'Kenyan Shilling', symbol: 'KSh' },
  TZS: { name: 'Tanzanian Shilling', symbol: 'TSh' },
  UGX: { name: 'Ugandan Shilling', symbol: 'USh' },
  ETB: { name: 'Ethiopian Birr', symbol: 'Br' },
  XOF: { name: 'West African CFA Franc', symbol: 'CFA' },
  XAF: { name: 'Central African CFA Franc', symbol: 'FCFA' },
  RUB: { name: 'Russian Ruble', symbol: '₽' },
  UAH: { name: 'Ukrainian Hryvnia', symbol: '₴' },
  VND: { name: 'Vietnamese Dong', symbol: '₫' },
  PKR: { name: 'Pakistani Rupee', symbol: '₨' },
  BDT: { name: 'Bangladeshi Taka', symbol: '৳' },
  LKR: { name: 'Sri Lankan Rupee', symbol: 'Rs' },
  NPR: { name: 'Nepalese Rupee', symbol: '₨' },
  MMK: { name: 'Myanmar Kyat', symbol: 'K' },
  KHR: { name: 'Cambodian Riel', symbol: '៛' },
  LAK: { name: 'Lao Kip', symbol: '₭' },
  TWD: { name: 'New Taiwan Dollar', symbol: 'NT$' },
  MOP: { name: 'Macanese Pataca', symbol: 'MOP$' },
  BND: { name: 'Brunei Dollar', symbol: 'B$' },
  CLP: { name: 'Chilean Peso', symbol: 'CLP$' },
  COP: { name: 'Colombian Peso', symbol: 'COL$' },
  PEN: { name: 'Peruvian Sol', symbol: 'S/' },
  UYU: { name: 'Uruguayan Peso', symbol: '$U' },
  BOB: { name: 'Bolivian Boliviano', symbol: 'Bs.' },
  PYG: { name: 'Paraguayan Guaraní', symbol: '₲' },
  VES: { name: 'Venezuelan Bolívar', symbol: 'Bs.' },
  CRC: { name: 'Costa Rican Colón', symbol: '₡' },
  GTQ: { name: 'Guatemalan Quetzal', symbol: 'Q' },
  HNL: { name: 'Honduran Lempira', symbol: 'L' },
  NIO: { name: 'Nicaraguan Córdoba', symbol: 'C$' },
  DOP: { name: 'Dominican Peso', symbol: 'RD$' },
  JMD: { name: 'Jamaican Dollar', symbol: 'J$' },
  TTD: { name: 'Trinidad & Tobago Dollar', symbol: 'TT$' },
  BSD: { name: 'Bahamian Dollar', symbol: 'B$' },
  BBD: { name: 'Barbadian Dollar', symbol: 'Bds$' },
  XCD: { name: 'East Caribbean Dollar', symbol: 'EC$' },
  PAB: { name: 'Panamanian Balboa', symbol: 'B/.' },
  KYD: { name: 'Cayman Islands Dollar', symbol: 'CI$' },
  BMD: { name: 'Bermudian Dollar', symbol: 'BD$' },
  HRK: { name: 'Croatian Kuna', symbol: 'kn' },
  RSD: { name: 'Serbian Dinar', symbol: 'дин.' },
  MKD: { name: 'Macedonian Denar', symbol: 'ден' },
  ALL: { name: 'Albanian Lek', symbol: 'L' },
  BAM: { name: 'Bosnia-Herzegovina Mark', symbol: 'KM' },
  MDL: { name: 'Moldovan Leu', symbol: 'L' },
  GEL: { name: 'Georgian Lari', symbol: '₾' },
  AMD: { name: 'Armenian Dram', symbol: '֏' },
  AZN: { name: 'Azerbaijani Manat', symbol: '₼' },
  BYN: { name: 'Belarusian Ruble', symbol: 'Br' },
  KZT: { name: 'Kazakhstani Tenge', symbol: '₸' },
  UZS: { name: 'Uzbekistani Som', symbol: 'soʻm' },
  KGS: { name: 'Kyrgyzstani Som', symbol: 'с' },
  TJS: { name: 'Tajikistani Somoni', symbol: 'SM' },
  TMT: { name: 'Turkmenistani Manat', symbol: 'm' },
  MNT: { name: 'Mongolian Tögrög', symbol: '₮' },
  AFN: { name: 'Afghan Afghani', symbol: '؋' },
  IRR: { name: 'Iranian Rial', symbol: '﷼' },
  IQD: { name: 'Iraqi Dinar', symbol: 'ع.د' },
  SYP: { name: 'Syrian Pound', symbol: '£S' },
  YER: { name: 'Yemeni Rial', symbol: '﷼' },
  LYD: { name: 'Libyan Dinar', symbol: 'ل.د' },
  SDG: { name: 'Sudanese Pound', symbol: 'ج.س.' },
  SOS: { name: 'Somali Shilling', symbol: 'Sh' },
  RWF: { name: 'Rwandan Franc', symbol: 'FRw' },
  BIF: { name: 'Burundian Franc', symbol: 'FBu' },
  CDF: { name: 'Congolese Franc', symbol: 'FC' },
  AOA: { name: 'Angolan Kwanza', symbol: 'Kz' },
  ZMW: { name: 'Zambian Kwacha', symbol: 'ZK' },
  MWK: { name: 'Malawian Kwacha', symbol: 'MK' },
  MZN: { name: 'Mozambican Metical', symbol: 'MT' },
  BWP: { name: 'Botswana Pula', symbol: 'P' },
  NAD: { name: 'Namibian Dollar', symbol: 'N$' },
  MUR: { name: 'Mauritian Rupee', symbol: '₨' },
  SCR: { name: 'Seychellois Rupee', symbol: '₨' },
  MGA: { name: 'Malagasy Ariary', symbol: 'Ar' },
  GMD: { name: 'Gambian Dalasi', symbol: 'D' },
  GNF: { name: 'Guinean Franc', symbol: 'FG' },
  SLL: { name: 'Sierra Leonean Leone', symbol: 'Le' },
  LRD: { name: 'Liberian Dollar', symbol: 'L$' },
  CVE: { name: 'Cape Verdean Escudo', symbol: '$' },
  SZL: { name: 'Eswatini Lilangeni', symbol: 'L' },
  LSL: { name: 'Lesotho Loti', symbol: 'L' },
  FJD: { name: 'Fijian Dollar', symbol: 'FJ$' },
  PGK: { name: 'Papua New Guinean Kina', symbol: 'K' },
  WST: { name: 'Samoan Tālā', symbol: 'WS$' },
  TOP: { name: 'Tongan Paʻanga', symbol: 'T$' },
  VUV: { name: 'Vanuatu Vatu', symbol: 'VT' },
  SBD: { name: 'Solomon Islands Dollar', symbol: 'SI$' },
  XPF: { name: 'CFP Franc', symbol: '₣' },
  MVR: { name: 'Maldivian Rufiyaa', symbol: '.ރ' },
  BTN: { name: 'Bhutanese Ngultrum', symbol: 'Nu.' },
};

/** Currency metadata for `code`, falling back to the bare code if unknown. */
export function currencyMeta(code: string): { code: string; name: string; symbol: string } {
  const c = code.toUpperCase();
  const meta = CURRENCY_CATALOG[c];
  return { code: c, name: meta?.name ?? c, symbol: meta?.symbol ?? c };
}
