<script lang="ts">
	/**
	 * The wallet exists.
	 *
	 * This is the first moment an address is shown, and that ordering is a rule
	 * rather than a layout choice: the core withholds `address` until the group
	 * has landed on-chain and the account is saved, because an address shown
	 * earlier is an address someone can fund before the wallet is reachable.
	 *
	 * The identicon is rendered from the address by the same core that derived
	 * it, so what the person memorises here is what every other client will
	 * draw.
	 */
	import Button from '$lib/ui/Button.svelte';
	import PasskeyProviderMark from './PasskeyProviderMark.svelte';
	import { keyBadge, providerLineFor } from '$lib/onboarding/core/copy';
	import { providerLabel } from '$lib/onboarding/core/passkey-directory.svelte';
	import { isDarkTheme } from '$lib/theme.svelte';
	import { identiconNormalizeSeed, identiconSvgCircular } from '$lib/onboarding/core/wasm-client';
	import type { CreateKeyRow } from '$lib/onboarding/generated/CreateKeyRow';

	interface Props {
		address: string;
		walletName: string;
		keys: CreateKeyRow[];
		strings: (key: string, params?: Record<string, string | number>) => string;
		onEnter: () => void;
	}

	let { address, walletName, keys, strings, onEnter }: Props = $props();

	/** "Copied" stands in for the address, then the address comes back. */
	let copied = $state(false);
	let copiedTimer: ReturnType<typeof setTimeout> | undefined;

	async function copy() {
		try {
			await navigator.clipboard.writeText(address);
		} catch {
			return; // A refused clipboard is not an error worth a dialog here.
		}
		copied = true;
		clearTimeout(copiedTimer);
		copiedTimer = setTimeout(() => (copied = false), 2000);
	}

	// The core owns seed normalization (spec 003's drift rule: never a local
	// toLowerCase). An unrenderable seed degrades to no artwork rather than
	// throwing on the one screen that must not fail.
	const identicon = $derived.by(() => {
		try {
			const seed = identiconNormalizeSeed(address);
			return seed.length === 0 ? null : identiconSvgCircular(seed);
		} catch {
			return null;
		}
	});
</script>

<section class="screen">
	<header class="intro">
		<div class="titlerow">
			<span class="tick" aria-hidden="true">
				<svg viewBox="0 0 24 24"><path d="M20 6 9 17l-5-5" /></svg>
			</span>
			<h1 class="title">{strings('onboarding.create.successTitle')}</h1>
		</div>
		<p class="subtitle">{strings('onboarding.create.successMessage', { count: keys.length })}</p>
	</header>

	<div class="card">
		<div class="identity">
			<span class="avatar" aria-hidden="true">
				{#if identicon}
					<!-- eslint-disable-next-line svelte/no-at-html-tags -- SVG generated by vela-core from the address, never user input -->
					{@html identicon}
				{/if}
			</span>
			<span class="wallet">{walletName}</span>
		</div>

		<!--
			The whole line is the copy target and the confirmation replaces it in
			place. The caption that used to sit above DESCRIBED the identicon — a
			sentence narrating a picture right next to it — and the "wallet
			address" label went for the same reason: a 42-character 0x string in
			mono under a wallet's name is not mistakable for anything else.
		-->
		<button
			class="address"
			type="button"
			onclick={copy}
			aria-label={strings('onboarding.common.copyAddress')}
			class:copied
		>
			{copied ? strings('onboarding.common.copied') : address}
		</button>
	</div>

	<ul class="keys">
		{#each keys as key, index (index)}
			{@const holder = providerLabel(key.provider_name, key.aaguid, isDarkTheme())}
			{@const where = holder ?? strings(providerLineFor(key.kind))}
			{@const badge = keyBadge(key, strings)}
			<li class="key">
				<!--
					The recap says the same three things the key list said, from the
					same fields (issue 207): the mark and the line answer WHERE the
					key lives, the badge answers only whether it is backed up. The
					glyph fallback is passed here too, so a row the catalog cannot
					name no longer leaves an empty leading slot and a ragged column.
				-->
				<PasskeyProviderMark {key} label={where} glyphFallback />
				<span class="keyname">
					{key.name}
					<span class="provider">{where}</span>
				</span>
				{#if badge}
					<span class="badge" data-tone={badge.tone}>{badge.text}</span>
				{/if}
			</li>
		{/each}
	</ul>

	<div class="spacer"></div>

	<Button variant="primary" shape="rounded" onclick={onEnter}>
		{strings('onboarding.create.enterWalletBtn')}
	</Button>
</section>

<style>
	.screen {
		display: flex;
		flex: 1;
		flex-direction: column;
		gap: var(--space-3xl);
	}

	.intro {
		display: flex;
		flex-direction: column;
		gap: var(--space-md);
	}

	.titlerow {
		display: flex;
		gap: var(--space-lg);
		align-items: center;
	}

	.tick {
		display: grid;
		flex: 0 0 var(--icon-xl);
		place-items: center;
		height: var(--icon-xl);
		border-radius: var(--radius-full);
		background: var(--color-success-soft);
	}

	.tick svg {
		width: var(--icon-base);
		height: var(--icon-base);
		fill: none;
		stroke: var(--color-success-base);
		stroke-width: var(--icon-stroke-heavy);
		stroke-linecap: round;
		stroke-linejoin: round;
	}

	.title {
		margin: 0;
		color: var(--color-fg-base);
		font-size: var(--text-3xl);
		font-weight: var(--weight-bold);
		line-height: var(--leading-tight);
		letter-spacing: -0.015em;
	}

	.subtitle {
		margin: 0;
		color: var(--color-fg-muted);
		font-size: var(--text-lg);
		line-height: var(--leading-normal);
	}

	.card {
		display: flex;
		flex-direction: column;
		gap: var(--space-xl);
		padding: var(--space-xl);
		border: var(--border-hairline) solid var(--color-border-base);
		border-radius: var(--radius-lg);
		background: var(--color-bg-sunken);
	}

	.identity {
		display: flex;
		gap: var(--space-xl);
		align-items: center;
	}

	.avatar {
		display: grid;
		flex: 0 0 var(--size-identiconDetail);
		place-items: center;
		width: var(--size-identiconDetail);
		height: var(--size-identiconDetail);
		border-radius: var(--radius-full);
		overflow: hidden;
	}

	.avatar :global(svg) {
		width: 100%;
		height: 100%;
	}

	.wallet {
		min-width: 0;
		color: var(--color-fg-base);
		font-size: var(--text-lg);
		font-weight: var(--weight-bold);
	}

	.address {
		padding: var(--space-lg) 0 0;
		border: 0;
		border-top: var(--border-hairline) solid var(--color-border-base);
		background: none;
		color: var(--color-fg-muted);
		font-family: var(--font-mono);
		font-size: var(--text-base);
		font-weight: var(--weight-medium);
		line-height: var(--leading-normal);
		text-align: left;
		overflow-wrap: anywhere;
		cursor: pointer;
	}

	.address:hover {
		color: var(--color-fg-base);
	}

	.address.copied {
		color: var(--color-success-base);
	}

	.keys {
		display: flex;
		flex-direction: column;
		margin: 0;
		padding: 0;
		list-style: none;
	}

	.key {
		display: flex;
		align-items: center;
		gap: var(--space-lg);
		padding-block: var(--space-lg);
		border-bottom: var(--border-hairline) solid var(--color-border-base);
	}

	/* The badge keeps the trailing edge; the name block takes what is left. */
	.keyname {
		display: flex;
		flex: 1;
		flex-direction: column;
		gap: var(--space-xs);
		min-width: 0;
		color: var(--color-fg-muted);
		font-size: var(--text-base);
	}

	/* Where the key lives, under its name. Quieter than the name: the name is
	   what the person chose, this is what the system reported. */
	.provider {
		color: var(--color-fg-subtle);
		font-size: var(--text-sm);
	}

	.badge {
		font-size: var(--text-sm);
		font-weight: var(--weight-semibold);
	}

	.badge[data-tone='synced'] {
		color: var(--color-success-base);
	}

	/* Neutral, not a warning. "Device-bound" is a KIND of passkey (a security
	   key, Windows Hello), not a fault: it cannot be synced, and there is
	   nothing to go and fix. A warning tone read as "go and sync this", which is
	   exactly what the owner ruled out. The real risk (every key device-bound)
	   is said by the "add a second key" hint, where it can be acted on. */
	.badge[data-tone='local'] {
		color: var(--color-fg-muted);
	}

	.spacer {
		flex: 1;
		min-height: var(--space-md);
	}
</style>
