//! Who is holding this passkey — resolved from the authenticator's AAGUID.
//!
//! Every registration reports a 128-bit AAGUID identifying the authenticator
//! MODEL (never the person, never the key). `iCloud 钥匙串`, `1Password`,
//! `Windows Hello`, `Samsung Pass` — that is the fact a key list needs, because
//! "where does this passkey live" is the question somebody is actually asking
//! when they look at one, and `此设备上的通行密钥` answers it for every key at
//! once.
//!
//! **The catalog is vendored, not queried.** aaguid-explorer.awesometools.dev
//! offers this lookup over HTTP; asking it would tell a third party which vault
//! holds a Vela wallet's key, which is exactly the kind of thing this wallet
//! exists not to leak. The table is compiled in
//! ([`passkey_catalog`](crate::passkey_catalog)), generated by
//! `scripts/gen-passkey-providers.mjs` from a reviewed file in the repo.
//!
//! **A miss is a normal answer, not an error.** The catalog covers software
//! passkey providers, not the hundreds of hardware models in the FIDO metadata
//! service, and an authenticator may report an all-zero AAGUID when attestation
//! is `none`. Callers degrade to what they already know — platform vs
//! cross-platform, the transports — which is what every client did before this
//! module existed.

use serde::{Deserialize, Serialize};

use crate::passkey_catalog::{ICONS, NO_ICON, PROVIDERS};

/// Artwork for the keys the catalog cannot name.
///
/// Hardware authenticators live in the FIDO metadata service, not in the
/// provider catalog, so a security key is the ONE unknown whose kind is still
/// known — the authenticator says `cross-platform`, and its transports say
/// whether it is the thing on the end of a USB cable. Drawing that is honest;
/// drawing a made-up brand mark would not be.
///
/// A platform authenticator with no catalog entry gets NO mark from here: all
/// that is known about it is "a passkey on this device", which each client
/// already draws in its own vocabulary.
///
/// Colours are placeholders rather than literals: these ship in one theme, and
/// one vendor's greys are not this app's greys in either theme. Callers
/// substitute their own tokens — the same contract `rasterize_svg_png` states.
const SECURITY_KEY_USB_SVG: &str = include_str!("../data/passkey-fallback-security-key.svg");
const SECURITY_KEY_SVG: &str = include_str!("../data/passkey-fallback-passkey.svg");

/// Which fallback a row deserves.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum FallbackMark {
    /// A key on the end of a USB cable.
    UsbKey,
    /// A security key reached some other way (NFC, BLE, hybrid).
    SecurityKey,
}

/// The three colour slots a fallback mark wears.
#[derive(Clone, Copy, Debug)]
pub struct MarkPalette<'a> {
    /// The body of the glyph — a muted foreground.
    pub strong: &'a str,
    /// The key's shell behind it — a border or sunken surface tone.
    pub soft: &'a str,
    /// What shows THROUGH the glyph: the surface the mark sits on, never white.
    pub hole: &'a str,
}

/// The transports a `get()` may put in `allowCredentials`.
///
/// The authenticator's own report is kept verbatim in the record — it is what
/// the device said about itself — but not all of it is safe to hand back to a
/// client. A YubiKey reports `usb,smart-card`: `smart-card` is a WebAuthn L3
/// transport, and while the spec says clients SHOULD ignore values they do not
/// know, Android's does not merely ignore it. It batches `allowCredentials` by
/// transport before talking CTAP, and an entry it cannot place is dropped —
/// which can empty the list it just filtered:
///
/// ```text
/// no credential match found as non-empty allowlist reduced to empty
/// when batching
/// ```
///
/// (device-found 2026-08-26). So the wire carries only the five transports a
/// client can actually route on. Dropping `smart-card` from a key that also
/// says `usb` loses nothing: the same key, reachable the same way.
#[must_use]
pub fn allowlist_transports(reported: &str) -> String {
    const ROUTABLE: [&str; 5] = ["usb", "nfc", "ble", "hybrid", "internal"];
    reported
        .split(',')
        .map(str::trim)
        .filter(|value| ROUTABLE.contains(value))
        .collect::<Vec<_>>()
        .join(",")
}

/// Which fallback mark, if any, a key row should draw when the catalog has no
/// entry for its AAGUID.
///
/// `None` means "nothing better than what you already draw" — a platform
/// authenticator, whose only honest description is the one the client already
/// shows.
#[must_use]
pub fn fallback_mark(
    authenticator_attachment: &str,
    transports: &str,
    chose_security_key: bool,
) -> Option<FallbackMark> {
    let transport = |name: &str| transports.split(',').any(|t| t.trim() == name);
    let cross_platform = authenticator_attachment == "cross-platform";
    if !cross_platform && !chose_security_key && !transport("usb") && !transport("nfc") {
        return None;
    }
    if transport("usb") {
        return Some(FallbackMark::UsbKey);
    }
    Some(FallbackMark::SecurityKey)
}

/// A fallback mark as SVG markup, wearing the caller's palette.
#[must_use]
pub fn fallback_svg(mark: FallbackMark, palette: MarkPalette) -> String {
    let source = match mark {
        FallbackMark::UsbKey => SECURITY_KEY_USB_SVG,
        FallbackMark::SecurityKey => SECURITY_KEY_SVG,
    };
    source
        .replace("{{strong}}", palette.strong)
        .replace("{{soft}}", palette.soft)
        .replace("{{hole}}", palette.hole)
}

/// A resolved authenticator model.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct PasskeyProvider {
    /// The canonical AAGUID, lowercase.
    pub aaguid: &'static str,
    /// The provider's own brand name, verbatim. NOT translated: "1Password" is
    /// "1Password" in every locale, and a translated brand is a wrong brand.
    pub name: &'static str,
    light: u16,
    dark: u16,
}

impl PasskeyProvider {
    /// The provider's mark as SVG markup for the given theme, falling back to
    /// the other theme's mark when only one is published.
    #[must_use]
    pub fn icon_svg(&self, dark: bool) -> Option<&'static str> {
        let (first, second) = if dark {
            (self.dark, self.light)
        } else {
            (self.light, self.dark)
        };
        for index in [first, second] {
            if index != NO_ICON {
                return ICONS.get(index as usize).copied();
            }
        }
        None
    }
}

/// The directory service that answers for models the compiled catalog does not
/// carry — hardware keys, and anything published since this build.
///
/// **Ours, not a third party's** (founder, 2026-08-26): it is a lookup service
/// that stores nothing, which is what makes asking it acceptable at all. The
/// bundled catalog still answers first and answers offline; this fills the gaps.
pub const AAGUID_DIRECTORY_ORIGIN: &str = "https://aaguid-explorer.awesometools.dev";

/// What the directory said about a model.
/// Serialized to the web as-is, hence camelCase: this crosses the wasm
/// boundary as a plain object rather than through a generated view type.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DirectoryEntry {
    /// The model's name, verbatim from the service.
    pub name: String,
    /// Absolute URL of its mark, when the entry has one this client can render.
    pub icon_url: Option<String>,
}

/// Where to ask about `aaguid`, or `None` when there is nothing to ask.
///
/// Returns `None` for a malformed, empty or all-zero AAGUID, and for one the
/// compiled catalog already answers: a request whose answer is already on the
/// device is a request that should not be made.
#[must_use]
pub fn directory_lookup_url(aaguid: &str) -> Option<String> {
    directory_lookup_url_at(AAGUID_DIRECTORY_ORIGIN, aaguid)
}

/// The same question, asked of a directory at `origin` — the one the person's
/// service-endpoint settings name (spec 038 #E4: the lookup is meant to go to
/// our own node, and which node is the shell's setting, not this crate's
/// constant). A trailing slash on the origin is tolerated.
#[must_use]
pub fn directory_lookup_url_at(origin: &str, aaguid: &str) -> Option<String> {
    let key = canonical(aaguid)?;
    if provider(&key).is_some() {
        return None;
    }
    let origin = origin.trim().trim_end_matches('/');
    if origin.is_empty() {
        return None;
    }
    Some(format!("{origin}/api/v1/authenticators/{key}"))
}

/// Read a directory response for `aaguid`, choosing the mark for the theme.
///
/// `None` unless the body is an object whose `id` is the AAGUID that was asked
/// about — the answer to somebody else's question is not an answer to this one
/// — and unless it carries a usable name. The icon path is checked against the
/// service's own shape before it becomes a URL: a client that will fetch
/// whatever a field says is a client that can be pointed anywhere.
#[must_use]
pub fn directory_entry(aaguid: &str, json: &str, dark: bool) -> Option<DirectoryEntry> {
    directory_entry_at(AAGUID_DIRECTORY_ORIGIN, aaguid, json, dark)
}

/// [`directory_entry`] for an answer from the directory at `origin`: the mark's
/// URL is built on the origin that was asked, never on the constant.
#[must_use]
pub fn directory_entry_at(
    origin: &str,
    aaguid: &str,
    json: &str,
    dark: bool,
) -> Option<DirectoryEntry> {
    let origin = origin.trim().trim_end_matches('/');
    let key = canonical(aaguid)?;
    let value: serde_json::Value = serde_json::from_str(json).ok()?;
    let id = value.get("id")?.as_str()?.trim().to_ascii_lowercase();
    if id != key {
        return None;
    }
    let name = value.get("name")?.as_str()?.trim().to_owned();
    if name.is_empty() {
        return None;
    }
    // `iconDark` is optional and often absent; the light mark is the fallback
    // in both directions, because a mark is better than no mark.
    let field = |name: &str| {
        value
            .get(name)
            .and_then(serde_json::Value::as_str)
            .filter(|path| icon_path_is_safe(path))
            .map(str::to_owned)
    };
    let icon_url = if dark {
        field("iconDark").or_else(|| field("icon"))
    } else {
        field("icon").or_else(|| field("iconDark"))
    }
    .map(|path| format!("{origin}/data/{path}"));
    Some(DirectoryEntry { name, icon_url })
}

/// `icons/<name>.svg|png`, and nothing else: no scheme, no traversal, no host.
fn icon_path_is_safe(path: &str) -> bool {
    let Some(file) = path.strip_prefix("icons/") else {
        return false;
    };
    let (stem, extension) = match file.rsplit_once('.') {
        Some(parts) => parts,
        None => return false,
    };
    let extension = extension.to_ascii_lowercase();
    (extension == "svg" || extension == "png")
        && !stem.is_empty()
        && stem
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_')
}

/// The lowercase canonical form, or `None` when there is no model to ask about.
fn canonical(aaguid: &str) -> Option<String> {
    let key = aaguid.trim().to_ascii_lowercase();
    if key.len() != 36 || key.bytes().all(|b| b == b'0' || b == b'-') {
        return None;
    }
    let shaped = key.bytes().enumerate().all(|(i, b)| match i {
        8 | 13 | 18 | 23 => b == b'-',
        _ => b.is_ascii_hexdigit(),
    });
    shaped.then_some(key)
}

/// Resolve an AAGUID to its provider. Input may be any case, with or without
/// surrounding whitespace; an empty or all-zero AAGUID resolves to `None`.
#[must_use]
pub fn provider(aaguid: &str) -> Option<PasskeyProvider> {
    let key = canonical(aaguid)?;
    let position = PROVIDERS
        .binary_search_by(|(candidate, ..)| (*candidate).cmp(key.as_str()))
        .ok()?;
    let (aaguid, name, light, dark) = PROVIDERS[position];
    Some(PasskeyProvider {
        aaguid,
        name,
        light,
        dark,
    })
}

/// What the registry's 20-byte attestation blob says about a credential
/// (`version ‖ AAGUID(16) ‖ authenticatorData flags ‖ reserved(2)`): the AAGUID
/// as a canonical uuid (empty when absent or all-zero), and whether the
/// credential is backed up (BS, bit 4) — a "synced passkey".
///
/// An EMPTY or malformed attestation reads as synced: some authenticators
/// legitimately omit attested-credential data, and everything that gates on
/// this must fail open rather than dead-end an honest provider. Shared by the
/// create flow's key list and the settings keys view (spec 062).
#[must_use]
pub fn attestation_signals(attestation_hex: &str) -> (String, bool) {
    let Ok(bytes) = crate::primitives::from_hex(attestation_hex) else {
        return (String::new(), true);
    };
    if bytes.len() != 20 {
        return (String::new(), true);
    }
    let aaguid_bytes = &bytes[1..17];
    let aaguid = if aaguid_bytes.iter().all(|b| *b == 0) {
        String::new()
    } else {
        let hex = crate::primitives::to_hex(aaguid_bytes, false);
        format!(
            "{}-{}-{}-{}-{}",
            &hex[0..8],
            &hex[8..12],
            &hex[12..16],
            &hex[16..20],
            &hex[20..32]
        )
    };
    let backed_up = bytes[17] & 0x10 != 0;
    (aaguid, backed_up)
}

/// Did the authenticator verify the person (UV, bit 2 of the flags byte) when
/// this credential was registered? `None` for an attestation this build cannot
/// read — unlike "synced", nothing gates on this, so it does not fail open: a
/// badge nobody can vouch for is not drawn.
#[must_use]
pub fn attestation_user_verified(attestation_hex: &str) -> Option<bool> {
    let bytes = crate::primitives::from_hex(attestation_hex).ok()?;
    (bytes.len() == 20).then(|| bytes[17] & 0x04 != 0)
}

/// The provider's brand name, or `None` when the catalog does not know it.
#[must_use]
pub fn provider_name(aaguid: &str) -> Option<&'static str> {
    provider(aaguid).map(|p| p.name)
}

/// The provider's mark as an `image/svg+xml` data URI.
///
/// A data URI rather than markup to inline: these SVGs carry `<style>` blocks
/// with generic class names (`.cls-1`) and `<clipPath id="…">`, so inlining
/// several of them into one document makes the last one's rules win for all of
/// them — the same id/class collision that once turned this app's identicons
/// square. Inside an `<img>`, each mark is its own document.
#[must_use]
pub fn provider_icon_data_uri(aaguid: &str, dark: bool) -> Option<String> {
    let svg = provider(aaguid)?.icon_svg(dark)?;
    Some(format!(
        "data:image/svg+xml;charset=utf-8,{}",
        percent_encode(svg)
    ))
}

/// A fallback mark as an `image/svg+xml` data URI, for the same reason the
/// provider marks are served that way.
#[must_use]
pub fn fallback_icon_data_uri(mark: FallbackMark, palette: MarkPalette) -> String {
    format!(
        "data:image/svg+xml;charset=utf-8,{}",
        percent_encode(&fallback_svg(mark, palette))
    )
}

/// Minimal percent-encoding for SVG in a data URI: only what a URI parser or an
/// HTML attribute would otherwise take for its own.
fn percent_encode(svg: &str) -> String {
    let mut out = String::with_capacity(svg.len() + svg.len() / 8);
    for byte in svg.bytes() {
        match byte {
            b'#' | b'%' | b'"' | b'\'' | b'<' | b'>' | b'?' | b'&' | b' ' => {
                out.push_str(&format!("%{byte:02X}"));
            }
            _ => out.push(byte as char),
        }
    }
    out
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;

    #[test]
    fn the_catalog_is_sorted_and_canonical() {
        for window in PROVIDERS.windows(2) {
            assert!(window[0].0 < window[1].0, "PROVIDERS must be sorted");
        }
        for (aaguid, name, ..) in PROVIDERS {
            assert_eq!(aaguid.len(), 36, "canonical uuid: {aaguid}");
            assert!(!name.is_empty(), "every provider is named");
        }
    }

    #[test]
    fn well_known_providers_resolve_in_any_case() {
        // Two the whole world sees; if the vendored file ever loses them, the
        // feature is silently useless for most people.
        assert_eq!(
            provider_name("fbfc3007-154e-4ecc-8c0b-6e020557d7bd"),
            // The dataset's own current name — Apple renamed it from iCloud
            // Keychain, and this catalog says what the vendor says.
            Some("Apple Passwords")
        );
        assert_eq!(
            provider_name("EA9B8D66-4D01-1D21-3CE4-B6B48CB575D4"),
            Some("Google Password Manager")
        );
        assert_eq!(
            provider_name("  08987058-cadc-4b81-b6e1-30de50dcbe96  "),
            Some("Windows Hello")
        );
    }

    #[test]
    fn a_miss_is_none_not_a_wrong_guess() {
        assert_eq!(provider_name(""), None);
        assert_eq!(provider_name("00000000-0000-0000-0000-000000000000"), None);
        assert_eq!(provider_name("not-a-uuid"), None);
        // A real YubiKey AAGUID: hardware keys live in the FIDO metadata
        // service, which this catalog deliberately does not carry.
        assert_eq!(provider_name("2fc0579f-8113-47ea-b116-bb5a8db9202a"), None);
    }

    #[test]
    fn every_provider_has_a_mark_in_both_themes() {
        for (aaguid, name, ..) in PROVIDERS {
            let p = provider(aaguid).expect("catalog entry resolves");
            // Two of the 55 publish no artwork at all; the rest must answer for
            // both themes (falling back across themes when only one exists).
            if p.icon_svg(false).is_none() {
                assert!(p.icon_svg(true).is_none(), "{name}: one-sided fallback");
            }
        }
    }

    const PALETTE: MarkPalette<'static> = MarkPalette {
        strong: "#6E6B62",
        soft: "#D8D4CB",
        hole: "#FAFAF8",
    };

    #[test]
    fn the_wire_carries_only_transports_a_client_can_route_on() {
        // A YubiKey's own report. `smart-card` is real and true, and Android
        // drops the whole descriptor over it.
        assert_eq!(allowlist_transports("usb,smart-card"), "usb");
        assert_eq!(allowlist_transports("nfc,usb,smart-card"), "nfc,usb");
        assert_eq!(allowlist_transports("hybrid,internal"), "hybrid,internal");
        assert_eq!(allowlist_transports(" usb , nfc "), "usb,nfc");
        // Nothing routable left is the same as saying nothing: the platform
        // then looks everywhere, which is better than looking nowhere.
        assert_eq!(allowlist_transports("smart-card"), "");
        assert_eq!(allowlist_transports(""), "");
    }

    #[test]
    fn a_usb_key_and_a_tapped_key_get_different_marks() {
        assert_eq!(
            fallback_mark("cross-platform", "usb,nfc", false),
            Some(FallbackMark::UsbKey)
        );
        assert_eq!(
            fallback_mark("cross-platform", "nfc", false),
            Some(FallbackMark::SecurityKey)
        );
        // The first key is minted before the key screen exists and carries the
        // core's default method, so what the DEVICE reported outranks it.
        assert_eq!(
            fallback_mark("", "usb", false),
            Some(FallbackMark::UsbKey),
            "the report outranks the default"
        );
        assert_eq!(
            fallback_mark("", "", true),
            Some(FallbackMark::SecurityKey),
            "and the person's own choice outranks silence"
        );
    }

    #[test]
    fn a_platform_authenticator_gets_no_fallback_mark() {
        // Its only honest description is "a passkey on this device", which every
        // client already draws in its own vocabulary.
        assert_eq!(fallback_mark("platform", "internal,hybrid", false), None);
        assert_eq!(fallback_mark("", "", false), None);
    }

    #[test]
    fn a_fallback_mark_wears_the_callers_palette_and_no_vendor_grey() {
        for mark in [FallbackMark::UsbKey, FallbackMark::SecurityKey] {
            let svg = fallback_svg(mark, PALETTE);
            assert!(svg.contains(PALETTE.strong), "the body takes fg");
            assert!(!svg.contains("{{"), "every slot is filled: {svg}");
            assert!(
                !svg.to_ascii_lowercase().contains("#5f6368"),
                "no vendor grey survives"
            );
            assert!(
                !svg.to_ascii_lowercase().contains("white"),
                "the cut-outs show the surface, not paper"
            );
        }
    }

    #[test]
    fn the_directory_is_asked_only_about_models_we_cannot_name() {
        // Already in the compiled catalog: no request.
        assert_eq!(
            directory_lookup_url("fbfc3007-154e-4ecc-8c0b-6e020557d7bd"),
            None
        );
        // A hardware key: ask.
        assert_eq!(
            directory_lookup_url("2FC0579F-8113-47EA-B116-BB5A8DB9202A").as_deref(),
            Some(
                "https://aaguid-explorer.awesometools.dev/api/v1/authenticators/\
                 2fc0579f-8113-47ea-b116-bb5a8db9202a"
            )
        );
        // Nothing to ask about.
        assert_eq!(directory_lookup_url(""), None);
        assert_eq!(
            directory_lookup_url("00000000-0000-0000-0000-000000000000"),
            None
        );
        assert_eq!(directory_lookup_url("../../etc/passwd"), None);
    }

    /// Spec 038 #E4: the directory is whichever node the settings name.
    #[test]
    fn the_directory_can_be_our_own_node() {
        let asked = "2fc0579f-8113-47ea-b116-bb5a8db9202a";
        assert_eq!(
            directory_lookup_url_at("https://aaguid.getvela.app/", asked).as_deref(),
            Some("https://aaguid.getvela.app/api/v1/authenticators/2fc0579f-8113-47ea-b116-bb5a8db9202a")
        );
        // The catalog still answers first, whichever node is named.
        assert_eq!(
            directory_lookup_url_at(
                "https://aaguid.getvela.app",
                "fbfc3007-154e-4ecc-8c0b-6e020557d7bd"
            ),
            None
        );
        // An empty origin is nowhere to ask, not the constant.
        assert_eq!(directory_lookup_url_at("  ", asked), None);
        let entry = directory_entry_at(
            "https://aaguid.getvela.app",
            asked,
            r#"{"id":"2fc0579f-8113-47ea-b116-bb5a8db9202a","name":"YubiKey 5 Series","icon":"icons/yubico.svg"}"#,
            false,
        )
        .expect("a well-formed answer");
        assert_eq!(
            entry.icon_url.as_deref(),
            Some("https://aaguid.getvela.app/data/icons/yubico.svg")
        );
    }

    #[test]
    fn a_directory_answer_must_be_about_the_question() {
        let asked = "2fc0579f-8113-47ea-b116-bb5a8db9202a";
        let entry = directory_entry(
            asked,
            r#"{"id":"2FC0579F-8113-47EA-B116-BB5A8DB9202A","name":"YubiKey 5 Series","icon":"icons/yubico.svg"}"#,
            false,
        )
        .expect("a well-formed answer");
        assert_eq!(entry.name, "YubiKey 5 Series");
        assert_eq!(
            entry.icon_url.as_deref(),
            Some("https://aaguid-explorer.awesometools.dev/data/icons/yubico.svg")
        );

        // Someone else's model, an empty name, or no JSON at all: no answer.
        assert_eq!(
            directory_entry(
                asked,
                r#"{"id":"ea9b8d66-4d01-1d21-3ce4-b6b48cb575d4","name":"x"}"#,
                false
            ),
            None
        );
        assert_eq!(
            directory_entry(
                asked,
                r#"{"id":"2fc0579f-8113-47ea-b116-bb5a8db9202a","name":"  "}"#,
                false
            ),
            None
        );
        assert_eq!(directory_entry(asked, "not json", false), None);

        // The dark cut when there is one, the light cut when there is not.
        let both = format!(
            r#"{{"id":"{asked}","name":"K","icon":"icons/a.png","iconDark":"icons/b.png"}}"#
        );
        assert!(directory_entry(asked, &both, true)
            .and_then(|e| e.icon_url)
            .is_some_and(|u| u.ends_with("icons/b.png")));
        assert!(directory_entry(asked, &both, false)
            .and_then(|e| e.icon_url)
            .is_some_and(|u| u.ends_with("icons/a.png")));
        let light_only = format!(r#"{{"id":"{asked}","name":"K","icon":"icons/a.png"}}"#);
        assert!(
            directory_entry(asked, &light_only, true)
                .and_then(|e| e.icon_url)
                .is_some_and(|u| u.ends_with("icons/a.png")),
            "a mark is better than no mark"
        );
    }

    #[test]
    fn an_icon_path_that_is_not_the_services_own_shape_is_dropped() {
        let asked = "2fc0579f-8113-47ea-b116-bb5a8db9202a";
        for icon in [
            "https://evil.example/x.svg",
            "icons/../../secret.svg",
            "icons/x.js",
            "/icons/x.svg",
            "x.svg",
        ] {
            let body = format!(r#"{{"id":"{asked}","name":"Some Key","icon":"{icon}"}}"#);
            let entry = directory_entry(asked, &body, false).expect("the name still stands");
            assert_eq!(entry.icon_url, None, "rejected: {icon}");
        }
    }

    #[test]
    fn data_uris_escape_what_an_attribute_would_eat() {
        let uri = provider_icon_data_uri("fbfc3007-154e-4ecc-8c0b-6e020557d7bd", false)
            .expect("Apple Passwords ships a mark");
        assert!(uri.starts_with("data:image/svg+xml;charset=utf-8,"));
        assert!(!uri.contains('"'), "quotes would close the src attribute");
        assert!(!uri.contains('#'), "a hash would truncate the URI");
        assert!(!uri.contains('<'), "angle brackets would reopen the markup");
    }
}
