// Builds the Vela Safari web-extension bundle into the apple-targets resources dir.
// Run: `node packages/safari-extension/build.mjs`  (or `npm run build` from here)
//
// Output goes into targets/safari/assets/, which @bacons/apple-targets links as the
// extension target's Resources (synchronized folder). MUST run AFTER `npx create-target
// safari` has scaffolded targets/safari/, and again after every `expo prebuild --clean`.
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { mkdirSync, copyFileSync, existsSync, writeFileSync } from 'node:fs';

const here = dirname(fileURLToPath(import.meta.url)); // packages/safari-extension
const repoRoot = resolve(here, '..', '..'); // vela-wallet
const SRC = resolve(here, 'src');
const OUT = resolve(repoRoot, 'targets', 'safari', 'assets'); // linked as target Resources

if (!existsSync(resolve(repoRoot, 'targets', 'safari'))) {
  console.warn(
    '[safari-extension] targets/safari/ does not exist yet — run `npx create-target safari` first.',
  );
}
mkdirSync(OUT, { recursive: true });

// JS: content.js + inpage.js + background.js + popup.js. Not minified so the
// PASS/echo logs stay readable in Web Inspector / the background console.
await build({
  entryPoints: [
    resolve(SRC, 'content.js'),
    resolve(SRC, 'inpage.js'),
    resolve(SRC, 'background.js'),
    resolve(SRC, 'popup.js'),
  ],
  outdir: OUT,
  bundle: true,
  format: 'iife',
  target: ['safari15'],
  minify: false,
  sourcemap: false,
  logLevel: 'info',
});

// Static assets: copy verbatim.
for (const f of ['manifest.json', 'popup.html']) {
  copyFileSync(resolve(SRC, f), resolve(OUT, f));
}

console.log('[safari-extension] wrote bundle ->', OUT);

// ---------------------------------------------------------------------------
// In-app WalletWebView provider bundle
// ---------------------------------------------------------------------------
// The SAME inpage.js + lib/protocol.js (+ the webview-inject shim) the Safari
// extension ships, bundled and emitted as a TS module the RN app imports and
// hands to the native WalletWebView (injected at document-start). Single source
// of truth → the Safari surface and the in-app browser can never drift.
// `write:false` keeps it out of the Safari Resources dir (it is not a Safari asset).
const injectResult = await build({
  entryPoints: [resolve(SRC, 'webview-inject.js')],
  bundle: true,
  format: 'iife',
  target: ['safari16', 'chrome109'], // iOS 16+ WKWebView / Android 12 (API 31) WebView
  minify: false,
  sourcemap: false,
  write: false,
  logLevel: 'info',
});
const injectSrc = injectResult.outputFiles[0].text;
const genDir = resolve(repoRoot, 'src', 'modules', 'webview');
mkdirSync(genDir, { recursive: true });
const genPath = resolve(genDir, 'injected-provider.generated.ts');
writeFileSync(
  genPath,
  '/* AUTO-GENERATED by packages/safari-extension/build.mjs — DO NOT EDIT.\n' +
    '   Single-sourced with the Safari extension: inpage.js + lib/protocol.js + webview-inject shim.\n' +
    '   Regenerate with `node packages/safari-extension/build.mjs`. */\n' +
    '/* eslint-disable */\n' +
    '// @ts-nocheck\n' +
    `export const INJECTED_PROVIDER_JS = ${JSON.stringify(injectSrc)};\n`,
  'utf8',
);
console.log('[safari-extension] wrote WalletWebView inject ->', genPath);
